# Generated by Django 2.1.1 on 2018-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_auto_20181030_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='info_url',
            field=models.CharField(default=' ', max_length=400),
            preserve_default=False,
        ),
    ]
