# Generated by Django 2.1.1 on 2018-11-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0003_shop_info_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
